language: java

jdk:
  - oraclejdk8

# don't run `gradle assemble` https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true
script:
- ./gradlew check
- ./gradlew -PpublishUsername=${SONATYPE_USERNAME} -PpublishPassword=${SONATYPE_PASSWORD} -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSWORD} -Psigning.secretKeyRingFile=secring.gpg uploadArchives

before_cache:
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/daemon/

cache:
  directories:
  - $HOME/.gradle

before_install:
  - openssl aes-256-cbc -K $encrypted_7a85652b67b9_key -iv $encrypted_7a85652b67b9_iv
    -in secring.gpg.enc -out secring.gpg -d

env:
  global:
    - GPG_KEY_ID: B17E37F8
    - secure: "IVoDVL/4fv5QoN2xKb4mSDsxM2HkNYTAYw4BW2z6WW9i77PGSGmnBqA4Mop0JzwfhyYw5zsDVDLP6h81UBHRTVgbfasAGwRl6aorsmAV0K9UF6m18mEyk41XtK23GnQX0ECARyYdlQdYTozpuK6BD4YwINPcwUGrGoA6zxe85ayLJncUfpRjemSlWm0t5QbdemGtx0jtrK0V1Ns8KkPfUeGIZRO9CS+TRTkDePLcOR3l4yhM+SP33XRLi3GfEhLhMPmtyUGf0l1IDQT9AcuC9R0YI2eijP+H/jha5U4gd+ytrgo6W6VBx/tFG5fe57jAq06fNzHaKW5YWIiRM38q6/jvk766SIx9tbjVxyiwA+XoWYpsd9BMrH4eH8RX+tYgSl5m/jUxfwTIxzxVyiB6g3sX9Z7asKUCho3ur67RAEOMiu7RvEpaWf3Xe0pppnfSHO9M1DYHg4bstD38u/IVHqsBg99LhzKZaodd07pE+CYk4tgKeUNp2n9AN12JHa6kQxCvljRlrXxhqrZn7oDvaBRhFU212Gj52JYtATYh9bPhE522LegypUR6S+NBc0BATfaOii320oNB1Cp7Ua1BOsxbmwsZ3Uyhth1v4VKKrz/rJLrVpB+fsdOC/JyQ0HJWq4PZ4YmZ7JadSfT5QrzscvZ0h9DSvad9Ce5eNc6fq/0="
    - secure: "RiD3yO4Nu+NzMaa+7UNbPr7bidL2MQNIsxE/wzqGtg5D1M81q8Kkug23Ye7F5vIjvlVgsAwFb977nm+diHqgWG76VGhvFX5V2YyzfpYKbnKHnw8ftPOEVwZZhBGzER6ImlWEU+5Ju8+w61K+LNyLhn1cmtEb+i3PWfJ5Lm1I6GY4ME/qY6vyXC0dQEHBqsRHXyfn/EJPAx2FwrX5K7yaxPiyAILiEQblV+wr7fWUskiGzDLpMS2bP9sNmUA/vaalxIgPaJn2uUxUh2C8uek+06Fm4kdtc4Mh3Y1PurDsAPs99krIPw/of3ywLi2kMFgU+UaXcj06EThZgXE/HJzjRrVCbiH2g/KTXfNuhZXUB6EkYxNHpVuXjnvsoowscquKFspEnvsceOlFJlG9gc2cBSyAWlLTHiebiCTccxenPuc0Jpmr1dh6PGhyalc1Z4Z1Wb0M6JUhzfOG7L2dWhKeEu8hM2dgih3tEYbAqb1fSZ16Wtbt/TCtXMVnnEbR9w2o6YOjDDhQsOxrBxqUinYKwf4UeqsvKGJ8MwhAGPGYwO+0XzuxESeFgi9CUwcwbZRkE8jTRG7/Dev7RE07UFCgmuNpTWAqU5BtJLuqUH0do8g7JLwFs9GTkp/WCb59SMcHeIh5EeYFng2XZBIuB3j9cbgm6XdQAU/kZ+3gHNtpj5w="
    - secure: "o0W61FL6toGf8+ztT19AD+tFvhVnaBC1UzVafW8eQpkcJXqnmVizieso1DJI/M13i6cUh1zTg+NZwj2Bee89O41Jp/txOVW/SLnVRANnC6kUa6dHVU8k+boxUbNrjeCkNPrWZ5YsxdfY3y1Ybp4qusOYqOdZw5dY2uOgaBFJzf/bn8IY6Moust2KLKZu84uyba2x4V0zq1HaMuu47Di+kfZZkZOLNLyiyZFp5SlslMToZVdtXaCMqJpelCLHsBAnt8wRSNw7D31qQDEShHpmziPdVORdfEXUaqcMTdBUHWDt27Y618JSV5ngg+V1ZSv+tIFsYF/ei+26MPEFLS2oiaeCl1jHRw8shIf8y/oG3l+yd7Tgz1K6V+ZLLcqS4N3BcjWqrfkEWgchqHJImRYw2/sGS1MfTAcVREyLhu6cObIhW31fpg7UVGk0vKN610veNLZ5Qe3Yjb3LStbhGPp1Vqz1DpgZB1TpUtxZdjCJfyp/Ky9lgvH4N3k7VFSG1iSBPexZFtTzW/r1u6MELxW9/lVhF4mmgvi7ljbOwbKtsLqARcJePnPa4vSZwAK7WmWm2xX8g8ds8a2w08JkZYqnAsc+/i7wMOEUNF6pYDXKg452ClOfNaPed8L5NYEbMYzwbJcjZ+zimhWAKYjNwtReMhGdARn8U4fkQMv/wZhoFMQ="

 
